const articles = [
  {
    id: 1,
    name: "Classic T-shirt",
    price: 19.99,
    description: "High quality cotton t-shirt",
    color: "White",
    size: ["S", "M", "L", "XL"],
    category: "Clothing",
    inStock: true,
    quantity: 50,
  },
  {
    id: 2,
    name: "Slim Jeans",
    price: 49.99,
    description: "Modern slim fit jeans",
    color: "Blue",
    size: ["36", "38", "40", "42"],
    category: "Pants",
    inStock: true,
    quantity: 30,
  },
  {
    id: 3,
    name: "Sport Sneakers",
    price: 79.99,
    description: "Comfortable sports shoes",
    color: "Black",
    size: ["38", "39", "40", "41", "42"],
    category: "Shoes",
    inStock: true,
    quantity: 25,
  },
  {
    id: 4,
    name: "Handbag",
    price: 29.99,
    description: "Elegant faux leather handbag",
    color: "Brown",
    size: ["One Size"],
    category: "Accessories",
    inStock: false,
    quantity: 0,
  },
  {
    id: 5,
    name: "Leather Jacket",
    price: 129.99,
    description: "Biker style leather jacket",
    color: "Black",
    size: ["S", "M", "L"],
    category: "Clothing",
    inStock: true,
    quantity: 15,
  },
  {
    id: 6,
    name: "Classic Watch",
    price: 89.99,
    description: "Elegant analog watch",
    color: "Silver",
    size: ["One Size"],
    category: "Accessories",
    inStock: true,
    quantity: 20,
  },
  {
    id: 7,
    name: "Business Shirt",
    price: 45.99,
    description: "Formal shirt for men",
    color: "White",
    size: ["S", "M", "L", "XL"],
    category: "Clothing",
    inStock: true,
    quantity: 35,
  },
  {
    id: 8,
    name: "Winter Scarf",
    price: 24.99,
    description: "Warm wool scarf",
    color: "Grey",
    size: ["One Size"],
    category: "Accessories",
    inStock: true,
    quantity: 40,
  },
  {
    id: 9,
    name: "Evening Dress",
    price: 99.99,
    description: "Elegant dress for special occasions",
    color: "Red",
    size: ["36", "38", "40", "42"],
    category: "Clothing",
    inStock: true,
    quantity: 10,
  },
  {
    id: 10,
    name: "Leather Belt",
    price: 34.99,
    description: "Genuine leather belt",
    color: "Brown",
    size: ["85", "90", "95", "100"],
    category: "Accessories",
    inStock: true,
    quantity: 45,
  },
];

export default articles;
