import { Movie } from "../../types";

export const sampleMovies: Movie[] = [
  {
    id: 1,
    title: "The Shawshank Redemption",
    poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    vote_average: 8.7,
    release_date: "1994-09-23",
    overview:
      "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
    backdrop_path: "/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    original_language: "en",
    original_title: "The Shawshank Redemption",
    popularity: 72.983,
    adult: false,
    video: false,
    vote_count: 24234,
    genre_ids: [18, 80],
  },
  {
    id: 2,
    title: "The Godfather",
    poster_path: "/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    vote_average: 8.7,
    release_date: "1972-03-14",
    overview:
      "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
    backdrop_path: "/tmU7GeKVybMWFButWEGl2M4GeiP.jpg",
    original_language: "en",
    original_title: "The Godfather",
    popularity: 91.234,
    adult: false,
    video: false,
    vote_count: 18321,
    genre_ids: [18, 80],
  },
  {
    id: 3,
    title: "The Dark Knight",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    vote_average: 8.5,
    release_date: "2008-07-16",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.",
    backdrop_path: "/nnMC0BM6XbjIIrT4miYmMtPGcQV.jpg",
    original_language: "en",
    original_title: "The Dark Knight",
    popularity: 78.123,
    adult: false,
    video: false,
    vote_count: 29034,
    genre_ids: [18, 28, 80, 53],
  },
];
